name: Terraform Validate

on:
  workflow_call:
    inputs:
      path:
        description: 'Path to Terraform module'
        required: true
        type: string
      terraform-version:
        description: 'Terraform version to use'
        required: false
        type: string
        default: '1.6.0'

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ inputs.terraform-version }}
      
      - name: Terraform Init
        working-directory: ${{ inputs.path }}
        run: |
          echo "🔧 Initializing ${{ inputs.path }}..."
          terraform init -backend=false
      
      - name: Terraform Validate
        working-directory: ${{ inputs.path }}
        run: |
          echo "✅ Validating ${{ inputs.path }}..."
          terraform validate
          echo "✅ Validation passed!"